########################################################
#           Alphagriffin.com                           #
# ==================================================== #
# Application: Python Key: value for options class.    #
#   - options.key = value                              #
########################################################

verbose: True

#//////| DATABASE |\\\\\\#
redis_host: 'localhost'
redis_pass: ' '

#//////| APP |\\\\\\#
input_text_path: 'text'
